service: nestjs-app

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    NODE_ENV: production
    DATABASE_URL: ${env:DATABASE_URL}
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PORT: ${env:REDIS_PORT}
    SESSION_SECRET: ${env:SESSION_SECRET}
    TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
    TWILIO_PHONE_NUMBER: ${env:TWILIO_PHONE_NUMBER}

functions:
  app:
    handler: dist/main.handler
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY
    layers:
      - { Ref: GraphicsLayer }

layers:
  GraphicsLayer:
    path: graphics-layer.zip # Path to your zipped layer file.

package:
  exclude:
    - node_modules/**
    - .env
    - test/**

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
